// Audit service protobuf definitions
// Provides gRPC endpoints for audit logging and compliance reporting

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: audit/audit_service.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogAccess logs an access event for audit trail
type LogAccessRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReferenceHash     string                 `protobuf:"bytes,1,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	Operation         string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // "tokenize" or "detokenize"
	RequestingService string                 `protobuf:"bytes,3,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	RequestingUser    string                 `protobuf:"bytes,4,opt,name=requesting_user,json=requestingUser,proto3" json:"requesting_user,omitempty"`
	Purpose           string                 `protobuf:"bytes,5,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientIp          string                 `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogAccessRequest) Reset() {
	*x = LogAccessRequest{}
	mi := &file_audit_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAccessRequest) ProtoMessage() {}

func (x *LogAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAccessRequest.ProtoReflect.Descriptor instead.
func (*LogAccessRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogAccessRequest) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *LogAccessRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LogAccessRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

func (x *LogAccessRequest) GetRequestingUser() string {
	if x != nil {
		return x.RequestingUser
	}
	return ""
}

func (x *LogAccessRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *LogAccessRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogAccessRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LogAccessRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAccessResponse) Reset() {
	*x = LogAccessResponse{}
	mi := &file_audit_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAccessResponse) ProtoMessage() {}

func (x *LogAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAccessResponse.ProtoReflect.Descriptor instead.
func (*LogAccessResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_service_proto_rawDescGZIP(), []int{1}
}

func (x *LogAccessResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *LogAccessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogAccessResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetAuditLogs retrieves audit logs based on criteria
type GetAuditLogsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ReferenceHash     string                 `protobuf:"bytes,3,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	RequestingService string                 `protobuf:"bytes,4,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	Limit             int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset            int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAuditLogsRequest) Reset() {
	*x = GetAuditLogsRequest{}
	mi := &file_audit_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsRequest) ProtoMessage() {}

func (x *GetAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetAuditLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetAuditLogsRequest) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *GetAuditLogsRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

func (x *GetAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAuditLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AuditLogEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuditId           string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	ReferenceHash     string                 `protobuf:"bytes,2,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	Operation         string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	RequestingService string                 `protobuf:"bytes,4,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	RequestingUser    string                 `protobuf:"bytes,5,opt,name=requesting_user,json=requestingUser,proto3" json:"requesting_user,omitempty"`
	Purpose           string                 `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientIp          string                 `protobuf:"bytes,8,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_audit_audit_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_audit_audit_service_proto_rawDescGZIP(), []int{3}
}

func (x *AuditLogEntry) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *AuditLogEntry) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *AuditLogEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AuditLogEntry) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

func (x *AuditLogEntry) GetRequestingUser() string {
	if x != nil {
		return x.RequestingUser
	}
	return ""
}

func (x *AuditLogEntry) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *AuditLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditLogEntry) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuditLogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLogEntry       `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_audit_audit_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuditLogsResponse) GetLogs() []*AuditLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetAuditLogsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAuditLogsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAuditLogsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_audit_audit_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_audit_audit_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_service_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_audit_audit_service_proto protoreflect.FileDescriptor

const file_audit_audit_service_proto_rawDesc = "" +
	"\n" +
	"\x19audit/audit_service.proto\x12\x05audit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x03\n" +
	"\x10LogAccessRequest\x12%\n" +
	"\x0ereference_hash\x18\x01 \x01(\tR\rreferenceHash\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12-\n" +
	"\x12requesting_service\x18\x03 \x01(\tR\x11requestingService\x12'\n" +
	"\x0frequesting_user\x18\x04 \x01(\tR\x0erequestingUser\x12\x18\n" +
	"\apurpose\x18\x05 \x01(\tR\apurpose\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\x12A\n" +
	"\bmetadata\x18\b \x03(\v2%.audit.LogAccessRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x11LogAccessResponse\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x8b\x02\n" +
	"\x13GetAuditLogsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12%\n" +
	"\x0ereference_hash\x18\x03 \x01(\tR\rreferenceHash\x12-\n" +
	"\x12requesting_service\x18\x04 \x01(\tR\x11requestingService\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"\xb5\x03\n" +
	"\rAuditLogEntry\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12%\n" +
	"\x0ereference_hash\x18\x02 \x01(\tR\rreferenceHash\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12-\n" +
	"\x12requesting_service\x18\x04 \x01(\tR\x11requestingService\x12'\n" +
	"\x0frequesting_user\x18\x05 \x01(\tR\x0erequestingUser\x12\x18\n" +
	"\apurpose\x18\x06 \x01(\tR\apurpose\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tclient_ip\x18\b \x01(\tR\bclientIp\x12>\n" +
	"\bmetadata\x18\t \x03(\v2\".audit.AuditLogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x14GetAuditLogsResponse\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.audit.AuditLogEntryR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xa3\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12A\n" +
	"\adetails\x18\x05 \x03(\v2'.audit.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdd\x01\n" +
	"\fAuditService\x12>\n" +
	"\tLogAccess\x12\x17.audit.LogAccessRequest\x1a\x18.audit.LogAccessResponse\x12G\n" +
	"\fGetAuditLogs\x12\x1a.audit.GetAuditLogsRequest\x1a\x1b.audit.GetAuditLogsResponse\x12D\n" +
	"\vHealthCheck\x12\x19.audit.HealthCheckRequest\x1a\x1a.audit.HealthCheckResponseB1Z/github.com/PlainFunction/mistokenly/proto/auditb\x06proto3"

var (
	file_audit_audit_service_proto_rawDescOnce sync.Once
	file_audit_audit_service_proto_rawDescData []byte
)

func file_audit_audit_service_proto_rawDescGZIP() []byte {
	file_audit_audit_service_proto_rawDescOnce.Do(func() {
		file_audit_audit_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_audit_service_proto_rawDesc), len(file_audit_audit_service_proto_rawDesc)))
	})
	return file_audit_audit_service_proto_rawDescData
}

var file_audit_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_audit_audit_service_proto_goTypes = []any{
	(*LogAccessRequest)(nil),      // 0: audit.LogAccessRequest
	(*LogAccessResponse)(nil),     // 1: audit.LogAccessResponse
	(*GetAuditLogsRequest)(nil),   // 2: audit.GetAuditLogsRequest
	(*AuditLogEntry)(nil),         // 3: audit.AuditLogEntry
	(*GetAuditLogsResponse)(nil),  // 4: audit.GetAuditLogsResponse
	(*HealthCheckRequest)(nil),    // 5: audit.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 6: audit.HealthCheckResponse
	nil,                           // 7: audit.LogAccessRequest.MetadataEntry
	nil,                           // 8: audit.AuditLogEntry.MetadataEntry
	nil,                           // 9: audit.HealthCheckResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_audit_audit_service_proto_depIdxs = []int32{
	10, // 0: audit.LogAccessRequest.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 1: audit.LogAccessRequest.metadata:type_name -> audit.LogAccessRequest.MetadataEntry
	10, // 2: audit.GetAuditLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	10, // 3: audit.GetAuditLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	10, // 4: audit.AuditLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: audit.AuditLogEntry.metadata:type_name -> audit.AuditLogEntry.MetadataEntry
	3,  // 6: audit.GetAuditLogsResponse.logs:type_name -> audit.AuditLogEntry
	10, // 7: audit.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 8: audit.HealthCheckResponse.details:type_name -> audit.HealthCheckResponse.DetailsEntry
	0,  // 9: audit.AuditService.LogAccess:input_type -> audit.LogAccessRequest
	2,  // 10: audit.AuditService.GetAuditLogs:input_type -> audit.GetAuditLogsRequest
	5,  // 11: audit.AuditService.HealthCheck:input_type -> audit.HealthCheckRequest
	1,  // 12: audit.AuditService.LogAccess:output_type -> audit.LogAccessResponse
	4,  // 13: audit.AuditService.GetAuditLogs:output_type -> audit.GetAuditLogsResponse
	6,  // 14: audit.AuditService.HealthCheck:output_type -> audit.HealthCheckResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_audit_audit_service_proto_init() }
func file_audit_audit_service_proto_init() {
	if File_audit_audit_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_audit_service_proto_rawDesc), len(file_audit_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_audit_service_proto_goTypes,
		DependencyIndexes: file_audit_audit_service_proto_depIdxs,
		MessageInfos:      file_audit_audit_service_proto_msgTypes,
	}.Build()
	File_audit_audit_service_proto = out.File
	file_audit_audit_service_proto_goTypes = nil
	file_audit_audit_service_proto_depIdxs = nil
}
