// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: persistence/persistence_service.proto

package persistence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StorePIITokenRequest represents a request to store a PII token
// This message is published to PGMQ queue by the PII service
type StorePIITokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReferenceHash  string                 `protobuf:"bytes,1,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	EncryptedData  []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Iv             []byte                 `protobuf:"bytes,3,opt,name=iv,proto3" json:"iv,omitempty"` // Initialization Vector for decryption
	DataType       string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	ClientId       string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorePIITokenRequest) Reset() {
	*x = StorePIITokenRequest{}
	mi := &file_persistence_persistence_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePIITokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePIITokenRequest) ProtoMessage() {}

func (x *StorePIITokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePIITokenRequest.ProtoReflect.Descriptor instead.
func (*StorePIITokenRequest) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{0}
}

func (x *StorePIITokenRequest) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *StorePIITokenRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *StorePIITokenRequest) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *StorePIITokenRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *StorePIITokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StorePIITokenRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *StorePIITokenRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StorePIITokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *StorePIITokenRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StorePIITokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceHash string                 `protobuf:"bytes,1,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorePIITokenResponse) Reset() {
	*x = StorePIITokenResponse{}
	mi := &file_persistence_persistence_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePIITokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePIITokenResponse) ProtoMessage() {}

func (x *StorePIITokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePIITokenResponse.ProtoReflect.Descriptor instead.
func (*StorePIITokenResponse) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{1}
}

func (x *StorePIITokenResponse) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *StorePIITokenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StorePIITokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RetrievePIITokenRequest represents a request to retrieve a PII token
type RetrievePIITokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReferenceHash  string                 `protobuf:"bytes,1,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // For access control verification
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrievePIITokenRequest) Reset() {
	*x = RetrievePIITokenRequest{}
	mi := &file_persistence_persistence_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievePIITokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievePIITokenRequest) ProtoMessage() {}

func (x *RetrievePIITokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievePIITokenRequest.ProtoReflect.Descriptor instead.
func (*RetrievePIITokenRequest) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{2}
}

func (x *RetrievePIITokenRequest) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *RetrievePIITokenRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type RetrievePIITokenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReferenceHash  string                 `protobuf:"bytes,1,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	EncryptedData  []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Iv             []byte                 `protobuf:"bytes,3,opt,name=iv,proto3" json:"iv,omitempty"`
	DataType       string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	ClientId       string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	ErrorMessage   string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrievePIITokenResponse) Reset() {
	*x = RetrievePIITokenResponse{}
	mi := &file_persistence_persistence_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievePIITokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievePIITokenResponse) ProtoMessage() {}

func (x *RetrievePIITokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievePIITokenResponse.ProtoReflect.Descriptor instead.
func (*RetrievePIITokenResponse) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{3}
}

func (x *RetrievePIITokenResponse) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *RetrievePIITokenResponse) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *RetrievePIITokenResponse) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *RetrievePIITokenResponse) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *RetrievePIITokenResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RetrievePIITokenResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RetrievePIITokenResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RetrievePIITokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RetrievePIITokenResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RetrievePIITokenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RetrievePIITokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_persistence_persistence_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_persistence_persistence_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// StoreTEKRequest represents a request to store a TEK for an organization
type StoreTEKRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	EncryptedTek   []byte                 `protobuf:"bytes,2,opt,name=encrypted_tek,json=encryptedTek,proto3" json:"encrypted_tek,omitempty"` // TEK encrypted with KEK
	OrgKeyHash     string                 `protobuf:"bytes,3,opt,name=org_key_hash,json=orgKeyHash,proto3" json:"org_key_hash,omitempty"`     // SHA-256 hash of organization key
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RotatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=rotated_at,json=rotatedAt,proto3" json:"rotated_at,omitempty"` // Nullable
	Version        int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreTEKRequest) Reset() {
	*x = StoreTEKRequest{}
	mi := &file_persistence_persistence_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTEKRequest) ProtoMessage() {}

func (x *StoreTEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTEKRequest.ProtoReflect.Descriptor instead.
func (*StoreTEKRequest) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{6}
}

func (x *StoreTEKRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *StoreTEKRequest) GetEncryptedTek() []byte {
	if x != nil {
		return x.EncryptedTek
	}
	return nil
}

func (x *StoreTEKRequest) GetOrgKeyHash() string {
	if x != nil {
		return x.OrgKeyHash
	}
	return ""
}

func (x *StoreTEKRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StoreTEKRequest) GetRotatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RotatedAt
	}
	return nil
}

func (x *StoreTEKRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StoreTEKResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreTEKResponse) Reset() {
	*x = StoreTEKResponse{}
	mi := &file_persistence_persistence_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTEKResponse) ProtoMessage() {}

func (x *StoreTEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTEKResponse.ProtoReflect.Descriptor instead.
func (*StoreTEKResponse) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{7}
}

func (x *StoreTEKResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *StoreTEKResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoreTEKResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RetrieveTEKRequest represents a request to retrieve a TEK for an organization
type RetrieveTEKRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationKey string                 `protobuf:"bytes,2,opt,name=organization_key,json=organizationKey,proto3" json:"organization_key,omitempty"` // For verification
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveTEKRequest) Reset() {
	*x = RetrieveTEKRequest{}
	mi := &file_persistence_persistence_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveTEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveTEKRequest) ProtoMessage() {}

func (x *RetrieveTEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveTEKRequest.ProtoReflect.Descriptor instead.
func (*RetrieveTEKRequest) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveTEKRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RetrieveTEKRequest) GetOrganizationKey() string {
	if x != nil {
		return x.OrganizationKey
	}
	return ""
}

type RetrieveTEKResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	EncryptedTek   []byte                 `protobuf:"bytes,2,opt,name=encrypted_tek,json=encryptedTek,proto3" json:"encrypted_tek,omitempty"` // TEK encrypted with KEK
	OrgKeyHash     string                 `protobuf:"bytes,3,opt,name=org_key_hash,json=orgKeyHash,proto3" json:"org_key_hash,omitempty"`     // SHA-256 hash of organization key
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RotatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=rotated_at,json=rotatedAt,proto3" json:"rotated_at,omitempty"` // Nullable
	Version        int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrieveTEKResponse) Reset() {
	*x = RetrieveTEKResponse{}
	mi := &file_persistence_persistence_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveTEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveTEKResponse) ProtoMessage() {}

func (x *RetrieveTEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_persistence_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveTEKResponse.ProtoReflect.Descriptor instead.
func (*RetrieveTEKResponse) Descriptor() ([]byte, []int) {
	return file_persistence_persistence_service_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveTEKResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RetrieveTEKResponse) GetEncryptedTek() []byte {
	if x != nil {
		return x.EncryptedTek
	}
	return nil
}

func (x *RetrieveTEKResponse) GetOrgKeyHash() string {
	if x != nil {
		return x.OrgKeyHash
	}
	return ""
}

func (x *RetrieveTEKResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RetrieveTEKResponse) GetRotatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RotatedAt
	}
	return nil
}

func (x *RetrieveTEKResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RetrieveTEKResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RetrieveTEKResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_persistence_persistence_service_proto protoreflect.FileDescriptor

const file_persistence_persistence_service_proto_rawDesc = "" +
	"\n" +
	"%persistence/persistence_service.proto\x12\vpersistence\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x03\n" +
	"\x14StorePIITokenRequest\x12%\n" +
	"\x0ereference_hash\x18\x01 \x01(\tR\rreferenceHash\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fR\rencryptedData\x12\x0e\n" +
	"\x02iv\x18\x03 \x01(\fR\x02iv\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12K\n" +
	"\bmetadata\x18\t \x03(\v2/.persistence.StorePIITokenRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x15StorePIITokenResponse\x12%\n" +
	"\x0ereference_hash\x18\x01 \x01(\tR\rreferenceHash\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"i\n" +
	"\x17RetrievePIITokenRequest\x12%\n" +
	"\x0ereference_hash\x18\x01 \x01(\tR\rreferenceHash\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\x9c\x04\n" +
	"\x18RetrievePIITokenResponse\x12%\n" +
	"\x0ereference_hash\x18\x01 \x01(\tR\rreferenceHash\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fR\rencryptedData\x12\x0e\n" +
	"\x02iv\x18\x03 \x01(\fR\x02iv\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12O\n" +
	"\bmetadata\x18\t \x03(\v23.persistence.RetrievePIITokenResponse.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xa9\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\adetails\x18\x05 \x03(\v2-.persistence.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x02\n" +
	"\x0fStoreTEKRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12#\n" +
	"\rencrypted_tek\x18\x02 \x01(\fR\fencryptedTek\x12 \n" +
	"\forg_key_hash\x18\x03 \x01(\tR\n" +
	"orgKeyHash\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"rotated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trotatedAt\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"x\n" +
	"\x10StoreTEKResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"h\n" +
	"\x12RetrieveTEKRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10organization_key\x18\x02 \x01(\tR\x0forganizationKey\"\xd2\x02\n" +
	"\x13RetrieveTEKResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12#\n" +
	"\rencrypted_tek\x18\x02 \x01(\fR\fencryptedTek\x12 \n" +
	"\forg_key_hash\x18\x03 \x01(\tR\n" +
	"orgKeyHash\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"rotated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trotatedAt\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage2\xba\x03\n" +
	"\x12PersistenceService\x12V\n" +
	"\rStorePIIToken\x12!.persistence.StorePIITokenRequest\x1a\".persistence.StorePIITokenResponse\x12_\n" +
	"\x10RetrievePIIToken\x12$.persistence.RetrievePIITokenRequest\x1a%.persistence.RetrievePIITokenResponse\x12G\n" +
	"\bStoreTEK\x12\x1c.persistence.StoreTEKRequest\x1a\x1d.persistence.StoreTEKResponse\x12P\n" +
	"\vRetrieveTEK\x12\x1f.persistence.RetrieveTEKRequest\x1a .persistence.RetrieveTEKResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.persistence.HealthCheckRequest\x1a .persistence.HealthCheckResponseB7Z5github.com/PlainFunction/mistokenly/proto/persistenceb\x06proto3"

var (
	file_persistence_persistence_service_proto_rawDescOnce sync.Once
	file_persistence_persistence_service_proto_rawDescData []byte
)

func file_persistence_persistence_service_proto_rawDescGZIP() []byte {
	file_persistence_persistence_service_proto_rawDescOnce.Do(func() {
		file_persistence_persistence_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_persistence_persistence_service_proto_rawDesc), len(file_persistence_persistence_service_proto_rawDesc)))
	})
	return file_persistence_persistence_service_proto_rawDescData
}

var file_persistence_persistence_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_persistence_persistence_service_proto_goTypes = []any{
	(*StorePIITokenRequest)(nil),     // 0: persistence.StorePIITokenRequest
	(*StorePIITokenResponse)(nil),    // 1: persistence.StorePIITokenResponse
	(*RetrievePIITokenRequest)(nil),  // 2: persistence.RetrievePIITokenRequest
	(*RetrievePIITokenResponse)(nil), // 3: persistence.RetrievePIITokenResponse
	(*HealthCheckRequest)(nil),       // 4: persistence.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 5: persistence.HealthCheckResponse
	(*StoreTEKRequest)(nil),          // 6: persistence.StoreTEKRequest
	(*StoreTEKResponse)(nil),         // 7: persistence.StoreTEKResponse
	(*RetrieveTEKRequest)(nil),       // 8: persistence.RetrieveTEKRequest
	(*RetrieveTEKResponse)(nil),      // 9: persistence.RetrieveTEKResponse
	nil,                              // 10: persistence.StorePIITokenRequest.MetadataEntry
	nil,                              // 11: persistence.RetrievePIITokenResponse.MetadataEntry
	nil,                              // 12: persistence.HealthCheckResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_persistence_persistence_service_proto_depIdxs = []int32{
	13, // 0: persistence.StorePIITokenRequest.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: persistence.StorePIITokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	10, // 2: persistence.StorePIITokenRequest.metadata:type_name -> persistence.StorePIITokenRequest.MetadataEntry
	13, // 3: persistence.RetrievePIITokenResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: persistence.RetrievePIITokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	11, // 5: persistence.RetrievePIITokenResponse.metadata:type_name -> persistence.RetrievePIITokenResponse.MetadataEntry
	13, // 6: persistence.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	12, // 7: persistence.HealthCheckResponse.details:type_name -> persistence.HealthCheckResponse.DetailsEntry
	13, // 8: persistence.StoreTEKRequest.created_at:type_name -> google.protobuf.Timestamp
	13, // 9: persistence.StoreTEKRequest.rotated_at:type_name -> google.protobuf.Timestamp
	13, // 10: persistence.RetrieveTEKResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 11: persistence.RetrieveTEKResponse.rotated_at:type_name -> google.protobuf.Timestamp
	0,  // 12: persistence.PersistenceService.StorePIIToken:input_type -> persistence.StorePIITokenRequest
	2,  // 13: persistence.PersistenceService.RetrievePIIToken:input_type -> persistence.RetrievePIITokenRequest
	6,  // 14: persistence.PersistenceService.StoreTEK:input_type -> persistence.StoreTEKRequest
	8,  // 15: persistence.PersistenceService.RetrieveTEK:input_type -> persistence.RetrieveTEKRequest
	4,  // 16: persistence.PersistenceService.HealthCheck:input_type -> persistence.HealthCheckRequest
	1,  // 17: persistence.PersistenceService.StorePIIToken:output_type -> persistence.StorePIITokenResponse
	3,  // 18: persistence.PersistenceService.RetrievePIIToken:output_type -> persistence.RetrievePIITokenResponse
	7,  // 19: persistence.PersistenceService.StoreTEK:output_type -> persistence.StoreTEKResponse
	9,  // 20: persistence.PersistenceService.RetrieveTEK:output_type -> persistence.RetrieveTEKResponse
	5,  // 21: persistence.PersistenceService.HealthCheck:output_type -> persistence.HealthCheckResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_persistence_persistence_service_proto_init() }
func file_persistence_persistence_service_proto_init() {
	if File_persistence_persistence_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_persistence_persistence_service_proto_rawDesc), len(file_persistence_persistence_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_persistence_persistence_service_proto_goTypes,
		DependencyIndexes: file_persistence_persistence_service_proto_depIdxs,
		MessageInfos:      file_persistence_persistence_service_proto_msgTypes,
	}.Build()
	File_persistence_persistence_service_proto = out.File
	file_persistence_persistence_service_proto_goTypes = nil
	file_persistence_persistence_service_proto_depIdxs = nil
}
