// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: persistence/persistence_service.proto

package persistence

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PersistenceService_StorePIIToken_FullMethodName    = "/persistence.PersistenceService/StorePIIToken"
	PersistenceService_RetrievePIIToken_FullMethodName = "/persistence.PersistenceService/RetrievePIIToken"
	PersistenceService_StoreTEK_FullMethodName         = "/persistence.PersistenceService/StoreTEK"
	PersistenceService_RetrieveTEK_FullMethodName      = "/persistence.PersistenceService/RetrieveTEK"
	PersistenceService_HealthCheck_FullMethodName      = "/persistence.PersistenceService/HealthCheck"
)

// PersistenceServiceClient is the client API for PersistenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PersistenceService handles durable storage of PII tokens and TEKs
type PersistenceServiceClient interface {
	// StorePIIToken stores a tokenized PII record durably
	StorePIIToken(ctx context.Context, in *StorePIITokenRequest, opts ...grpc.CallOption) (*StorePIITokenResponse, error)
	// RetrievePIIToken retrieves a tokenized PII record from persistent storage
	RetrievePIIToken(ctx context.Context, in *RetrievePIITokenRequest, opts ...grpc.CallOption) (*RetrievePIITokenResponse, error)
	// StoreTEK stores a Tenant Encryption Key for an organization
	StoreTEK(ctx context.Context, in *StoreTEKRequest, opts ...grpc.CallOption) (*StoreTEKResponse, error)
	// RetrieveTEK retrieves a Tenant Encryption Key for an organization
	RetrieveTEK(ctx context.Context, in *RetrieveTEKRequest, opts ...grpc.CallOption) (*RetrieveTEKResponse, error)
	// HealthCheck returns the health status of the persistence service
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type persistenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistenceServiceClient(cc grpc.ClientConnInterface) PersistenceServiceClient {
	return &persistenceServiceClient{cc}
}

func (c *persistenceServiceClient) StorePIIToken(ctx context.Context, in *StorePIITokenRequest, opts ...grpc.CallOption) (*StorePIITokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorePIITokenResponse)
	err := c.cc.Invoke(ctx, PersistenceService_StorePIIToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) RetrievePIIToken(ctx context.Context, in *RetrievePIITokenRequest, opts ...grpc.CallOption) (*RetrievePIITokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrievePIITokenResponse)
	err := c.cc.Invoke(ctx, PersistenceService_RetrievePIIToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) StoreTEK(ctx context.Context, in *StoreTEKRequest, opts ...grpc.CallOption) (*StoreTEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreTEKResponse)
	err := c.cc.Invoke(ctx, PersistenceService_StoreTEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) RetrieveTEK(ctx context.Context, in *RetrieveTEKRequest, opts ...grpc.CallOption) (*RetrieveTEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveTEKResponse)
	err := c.cc.Invoke(ctx, PersistenceService_RetrieveTEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PersistenceService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistenceServiceServer is the server API for PersistenceService service.
// All implementations must embed UnimplementedPersistenceServiceServer
// for forward compatibility.
//
// PersistenceService handles durable storage of PII tokens and TEKs
type PersistenceServiceServer interface {
	// StorePIIToken stores a tokenized PII record durably
	StorePIIToken(context.Context, *StorePIITokenRequest) (*StorePIITokenResponse, error)
	// RetrievePIIToken retrieves a tokenized PII record from persistent storage
	RetrievePIIToken(context.Context, *RetrievePIITokenRequest) (*RetrievePIITokenResponse, error)
	// StoreTEK stores a Tenant Encryption Key for an organization
	StoreTEK(context.Context, *StoreTEKRequest) (*StoreTEKResponse, error)
	// RetrieveTEK retrieves a Tenant Encryption Key for an organization
	RetrieveTEK(context.Context, *RetrieveTEKRequest) (*RetrieveTEKResponse, error)
	// HealthCheck returns the health status of the persistence service
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPersistenceServiceServer()
}

// UnimplementedPersistenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPersistenceServiceServer struct{}

func (UnimplementedPersistenceServiceServer) StorePIIToken(context.Context, *StorePIITokenRequest) (*StorePIITokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorePIIToken not implemented")
}
func (UnimplementedPersistenceServiceServer) RetrievePIIToken(context.Context, *RetrievePIITokenRequest) (*RetrievePIITokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrievePIIToken not implemented")
}
func (UnimplementedPersistenceServiceServer) StoreTEK(context.Context, *StoreTEKRequest) (*StoreTEKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTEK not implemented")
}
func (UnimplementedPersistenceServiceServer) RetrieveTEK(context.Context, *RetrieveTEKRequest) (*RetrieveTEKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTEK not implemented")
}
func (UnimplementedPersistenceServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPersistenceServiceServer) mustEmbedUnimplementedPersistenceServiceServer() {}
func (UnimplementedPersistenceServiceServer) testEmbeddedByValue()                            {}

// UnsafePersistenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistenceServiceServer will
// result in compilation errors.
type UnsafePersistenceServiceServer interface {
	mustEmbedUnimplementedPersistenceServiceServer()
}

func RegisterPersistenceServiceServer(s grpc.ServiceRegistrar, srv PersistenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedPersistenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PersistenceService_ServiceDesc, srv)
}

func _PersistenceService_StorePIIToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePIITokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).StorePIIToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_StorePIIToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).StorePIIToken(ctx, req.(*StorePIITokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_RetrievePIIToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievePIITokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).RetrievePIIToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_RetrievePIIToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).RetrievePIIToken(ctx, req.(*RetrievePIITokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_StoreTEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).StoreTEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_StoreTEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).StoreTEK(ctx, req.(*StoreTEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_RetrieveTEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveTEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).RetrieveTEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_RetrieveTEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).RetrieveTEK(ctx, req.(*RetrieveTEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersistenceService_ServiceDesc is the grpc.ServiceDesc for PersistenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersistenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "persistence.PersistenceService",
	HandlerType: (*PersistenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StorePIIToken",
			Handler:    _PersistenceService_StorePIIToken_Handler,
		},
		{
			MethodName: "RetrievePIIToken",
			Handler:    _PersistenceService_RetrievePIIToken_Handler,
		},
		{
			MethodName: "StoreTEK",
			Handler:    _PersistenceService_StoreTEK_Handler,
		},
		{
			MethodName: "RetrieveTEK",
			Handler:    _PersistenceService_RetrieveTEK_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PersistenceService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persistence/persistence_service.proto",
}
