// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pii/pii_service.proto

package pii

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenizeRequest contains PII data to be tokenized
type TokenizeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Data            string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	DataType        string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	RetentionPolicy string                 `protobuf:"bytes,3,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	ClientId        string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrganizationId  string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationKey string                 `protobuf:"bytes,7,opt,name=organization_key,json=organizationKey,proto3" json:"organization_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TokenizeRequest) Reset() {
	*x = TokenizeRequest{}
	mi := &file_pii_pii_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeRequest) ProtoMessage() {}

func (x *TokenizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pii_pii_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeRequest.ProtoReflect.Descriptor instead.
func (*TokenizeRequest) Descriptor() ([]byte, []int) {
	return file_pii_pii_service_proto_rawDescGZIP(), []int{0}
}

func (x *TokenizeRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TokenizeRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *TokenizeRequest) GetRetentionPolicy() string {
	if x != nil {
		return x.RetentionPolicy
	}
	return ""
}

func (x *TokenizeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TokenizeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TokenizeRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *TokenizeRequest) GetOrganizationKey() string {
	if x != nil {
		return x.OrganizationKey
	}
	return ""
}

// TokenizeResponse contains the generated reference token
type TokenizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceHash string                 `protobuf:"bytes,1,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenizeResponse) Reset() {
	*x = TokenizeResponse{}
	mi := &file_pii_pii_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeResponse) ProtoMessage() {}

func (x *TokenizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pii_pii_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeResponse.ProtoReflect.Descriptor instead.
func (*TokenizeResponse) Descriptor() ([]byte, []int) {
	return file_pii_pii_service_proto_rawDescGZIP(), []int{1}
}

func (x *TokenizeResponse) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *TokenizeResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenizeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TokenizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TokenizeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// DetokenizeRequest contains the reference token to be detokenized
type DetokenizeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReferenceHash     string                 `protobuf:"bytes,1,opt,name=reference_hash,json=referenceHash,proto3" json:"reference_hash,omitempty"`
	Purpose           string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	RequestingService string                 `protobuf:"bytes,3,opt,name=requesting_service,json=requestingService,proto3" json:"requesting_service,omitempty"`
	RequestingUser    string                 `protobuf:"bytes,4,opt,name=requesting_user,json=requestingUser,proto3" json:"requesting_user,omitempty"`
	OrganizationId    string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationKey   string                 `protobuf:"bytes,6,opt,name=organization_key,json=organizationKey,proto3" json:"organization_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetokenizeRequest) Reset() {
	*x = DetokenizeRequest{}
	mi := &file_pii_pii_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetokenizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetokenizeRequest) ProtoMessage() {}

func (x *DetokenizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pii_pii_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetokenizeRequest.ProtoReflect.Descriptor instead.
func (*DetokenizeRequest) Descriptor() ([]byte, []int) {
	return file_pii_pii_service_proto_rawDescGZIP(), []int{2}
}

func (x *DetokenizeRequest) GetReferenceHash() string {
	if x != nil {
		return x.ReferenceHash
	}
	return ""
}

func (x *DetokenizeRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *DetokenizeRequest) GetRequestingService() string {
	if x != nil {
		return x.RequestingService
	}
	return ""
}

func (x *DetokenizeRequest) GetRequestingUser() string {
	if x != nil {
		return x.RequestingUser
	}
	return ""
}

func (x *DetokenizeRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DetokenizeRequest) GetOrganizationKey() string {
	if x != nil {
		return x.OrganizationKey
	}
	return ""
}

// DetokenizeResponse contains the decrypted PII data
type DetokenizeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Data              string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	DataType          string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	OriginalTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=original_timestamp,json=originalTimestamp,proto3" json:"original_timestamp,omitempty"`
	AccessLogged      bool                   `protobuf:"varint,4,opt,name=access_logged,json=accessLogged,proto3" json:"access_logged,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetokenizeResponse) Reset() {
	*x = DetokenizeResponse{}
	mi := &file_pii_pii_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetokenizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetokenizeResponse) ProtoMessage() {}

func (x *DetokenizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pii_pii_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetokenizeResponse.ProtoReflect.Descriptor instead.
func (*DetokenizeResponse) Descriptor() ([]byte, []int) {
	return file_pii_pii_service_proto_rawDescGZIP(), []int{3}
}

func (x *DetokenizeResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DetokenizeResponse) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *DetokenizeResponse) GetOriginalTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OriginalTimestamp
	}
	return nil
}

func (x *DetokenizeResponse) GetAccessLogged() bool {
	if x != nil {
		return x.AccessLogged
	}
	return false
}

func (x *DetokenizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DetokenizeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HealthCheckRequest requests health status
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pii_pii_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pii_pii_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pii_pii_service_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// HealthCheckResponse contains health status information
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pii_pii_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pii_pii_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pii_pii_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_pii_pii_service_proto protoreflect.FileDescriptor

const file_pii_pii_service_proto_rawDesc = "" +
	"\n" +
	"\x15pii/pii_service.proto\x12\x03pii\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x0fTokenizeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12)\n" +
	"\x10retention_policy\x18\x03 \x01(\tR\x0fretentionPolicy\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".pii.TokenizeRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10organization_key\x18\a \x01(\tR\x0forganizationKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x10TokenizeResponse\x12%\n" +
	"\x0ereference_hash\x18\x01 \x01(\tR\rreferenceHash\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x80\x02\n" +
	"\x11DetokenizeRequest\x12%\n" +
	"\x0ereference_hash\x18\x01 \x01(\tR\rreferenceHash\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12-\n" +
	"\x12requesting_service\x18\x03 \x01(\tR\x11requestingService\x12'\n" +
	"\x0frequesting_user\x18\x04 \x01(\tR\x0erequestingUser\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10organization_key\x18\x06 \x01(\tR\x0forganizationKey\"\xf2\x01\n" +
	"\x12DetokenizeResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12I\n" +
	"\x12original_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x11originalTimestamp\x12#\n" +
	"\raccess_logged\x18\x04 \x01(\bR\faccessLogged\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xa1\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\adetails\x18\x05 \x03(\v2%.pii.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc6\x01\n" +
	"\n" +
	"PIIService\x127\n" +
	"\bTokenize\x12\x14.pii.TokenizeRequest\x1a\x15.pii.TokenizeResponse\x12=\n" +
	"\n" +
	"Detokenize\x12\x16.pii.DetokenizeRequest\x1a\x17.pii.DetokenizeResponse\x12@\n" +
	"\vHealthCheck\x12\x17.pii.HealthCheckRequest\x1a\x18.pii.HealthCheckResponseB/Z-github.com/PlainFunction/mistokenly/proto/piib\x06proto3"

var (
	file_pii_pii_service_proto_rawDescOnce sync.Once
	file_pii_pii_service_proto_rawDescData []byte
)

func file_pii_pii_service_proto_rawDescGZIP() []byte {
	file_pii_pii_service_proto_rawDescOnce.Do(func() {
		file_pii_pii_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pii_pii_service_proto_rawDesc), len(file_pii_pii_service_proto_rawDesc)))
	})
	return file_pii_pii_service_proto_rawDescData
}

var file_pii_pii_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pii_pii_service_proto_goTypes = []any{
	(*TokenizeRequest)(nil),       // 0: pii.TokenizeRequest
	(*TokenizeResponse)(nil),      // 1: pii.TokenizeResponse
	(*DetokenizeRequest)(nil),     // 2: pii.DetokenizeRequest
	(*DetokenizeResponse)(nil),    // 3: pii.DetokenizeResponse
	(*HealthCheckRequest)(nil),    // 4: pii.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 5: pii.HealthCheckResponse
	nil,                           // 6: pii.TokenizeRequest.MetadataEntry
	nil,                           // 7: pii.HealthCheckResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_pii_pii_service_proto_depIdxs = []int32{
	6, // 0: pii.TokenizeRequest.metadata:type_name -> pii.TokenizeRequest.MetadataEntry
	8, // 1: pii.TokenizeResponse.expires_at:type_name -> google.protobuf.Timestamp
	8, // 2: pii.DetokenizeResponse.original_timestamp:type_name -> google.protobuf.Timestamp
	8, // 3: pii.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	7, // 4: pii.HealthCheckResponse.details:type_name -> pii.HealthCheckResponse.DetailsEntry
	0, // 5: pii.PIIService.Tokenize:input_type -> pii.TokenizeRequest
	2, // 6: pii.PIIService.Detokenize:input_type -> pii.DetokenizeRequest
	4, // 7: pii.PIIService.HealthCheck:input_type -> pii.HealthCheckRequest
	1, // 8: pii.PIIService.Tokenize:output_type -> pii.TokenizeResponse
	3, // 9: pii.PIIService.Detokenize:output_type -> pii.DetokenizeResponse
	5, // 10: pii.PIIService.HealthCheck:output_type -> pii.HealthCheckResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pii_pii_service_proto_init() }
func file_pii_pii_service_proto_init() {
	if File_pii_pii_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pii_pii_service_proto_rawDesc), len(file_pii_pii_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pii_pii_service_proto_goTypes,
		DependencyIndexes: file_pii_pii_service_proto_depIdxs,
		MessageInfos:      file_pii_pii_service_proto_msgTypes,
	}.Build()
	File_pii_pii_service_proto = out.File
	file_pii_pii_service_proto_goTypes = nil
	file_pii_pii_service_proto_depIdxs = nil
}
