// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pii/pii_service.proto

package pii

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PIIService_Tokenize_FullMethodName    = "/pii.PIIService/Tokenize"
	PIIService_Detokenize_FullMethodName  = "/pii.PIIService/Detokenize"
	PIIService_HealthCheck_FullMethodName = "/pii.PIIService/HealthCheck"
)

// PIIServiceClient is the client API for PIIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PIIService handles PII tokenization and detokenization operations
type PIIServiceClient interface {
	// Tokenize encrypts and stores PII data, returning a reference token
	Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error)
	// Detokenize retrieves and decrypts PII data from a reference token
	Detokenize(ctx context.Context, in *DetokenizeRequest, opts ...grpc.CallOption) (*DetokenizeResponse, error)
	// HealthCheck returns the health status of the PII service
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type pIIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPIIServiceClient(cc grpc.ClientConnInterface) PIIServiceClient {
	return &pIIServiceClient{cc}
}

func (c *pIIServiceClient) Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenizeResponse)
	err := c.cc.Invoke(ctx, PIIService_Tokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pIIServiceClient) Detokenize(ctx context.Context, in *DetokenizeRequest, opts ...grpc.CallOption) (*DetokenizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetokenizeResponse)
	err := c.cc.Invoke(ctx, PIIService_Detokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pIIServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PIIService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PIIServiceServer is the server API for PIIService service.
// All implementations must embed UnimplementedPIIServiceServer
// for forward compatibility.
//
// PIIService handles PII tokenization and detokenization operations
type PIIServiceServer interface {
	// Tokenize encrypts and stores PII data, returning a reference token
	Tokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error)
	// Detokenize retrieves and decrypts PII data from a reference token
	Detokenize(context.Context, *DetokenizeRequest) (*DetokenizeResponse, error)
	// HealthCheck returns the health status of the PII service
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPIIServiceServer()
}

// UnimplementedPIIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPIIServiceServer struct{}

func (UnimplementedPIIServiceServer) Tokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tokenize not implemented")
}
func (UnimplementedPIIServiceServer) Detokenize(context.Context, *DetokenizeRequest) (*DetokenizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detokenize not implemented")
}
func (UnimplementedPIIServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPIIServiceServer) mustEmbedUnimplementedPIIServiceServer() {}
func (UnimplementedPIIServiceServer) testEmbeddedByValue()                    {}

// UnsafePIIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PIIServiceServer will
// result in compilation errors.
type UnsafePIIServiceServer interface {
	mustEmbedUnimplementedPIIServiceServer()
}

func RegisterPIIServiceServer(s grpc.ServiceRegistrar, srv PIIServiceServer) {
	// If the following call pancis, it indicates UnimplementedPIIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PIIService_ServiceDesc, srv)
}

func _PIIService_Tokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PIIServiceServer).Tokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PIIService_Tokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PIIServiceServer).Tokenize(ctx, req.(*TokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PIIService_Detokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PIIServiceServer).Detokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PIIService_Detokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PIIServiceServer).Detokenize(ctx, req.(*DetokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PIIService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PIIServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PIIService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PIIServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PIIService_ServiceDesc is the grpc.ServiceDesc for PIIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PIIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pii.PIIService",
	HandlerType: (*PIIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tokenize",
			Handler:    _PIIService_Tokenize_Handler,
		},
		{
			MethodName: "Detokenize",
			Handler:    _PIIService_Detokenize_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PIIService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pii/pii_service.proto",
}
